# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beg', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('passwd', models.EmailField(max_length=254)),
                ('email', models.CharField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='resa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srv.User'),
        ),
    ]
